name: Build and Release OpenOrchid

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Get Version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Build Electron App for Linux (ARM 32-bit)
        run: npm run build-linux-armv7h
        if: matrix.platform == 'linux-armv7h'

      - name: Build Electron App for Linux (ARM 64-bit)
        run: npm run build-linux-aarch64
        if: matrix.platform == 'linux-aarch64'

      - name: Build Electron App for Linux (x86_64)
        run: npm run build-linux-x86_64
        if: matrix.platform == 'linux-x86_64'

      - name: Build Electron App for Windows (x86)
        run: npm run build-win-ia32
        if: matrix.platform == 'win-ia32'

      - name: Build Electron App for Windows (x64)
        run: npm run build-win-x64
        if: matrix.platform == 'win-x64'

      - name: Build Electron App for macOS (arm64)
        run: npm run build-mac-arm64
        if: matrix.platform == 'mac-arm64'

      - name: Build Electron App for macOS (x64)
        run: npm run build-mac-x64
        if: matrix.platform == 'mac-x64'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Developer Beta v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Linux Release Asset (ARM 32-bit)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/openorchid-${{ steps.get_version.outputs.version }}-linux-armv7l.tar.gz
          asset_name: openorchid-${{ steps.get_version.outputs.version }}-linux-armv7l.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux Release Asset (ARM 64-bit)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/openorchid-${{ steps.get_version.outputs.version }}-linux-arm64.tar.gz
          asset_name: openorchid-${{ steps.get_version.outputs.version }}-linux-arm64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux Release Asset (x86)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/openorchid-${{ steps.get_version.outputs.version }}-linux-ia32.tar.gz
          asset_name: openorchid-${{ steps.get_version.outputs.version }}-linux-ia32.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux Release Asset (x64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/openorchid-${{ steps.get_version.outputs.version }}-linux-x64.tar.gz
          asset_name: openorchid-${{ steps.get_version.outputs.version }}-linux-x64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows Release Asset (x86)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/openorchid-${{ steps.get_version.outputs.version }}-win-ia32.zip
          asset_name: openorchid-${{ steps.get_version.outputs.version }}-win-ia32.zip
          asset_content_type: application/octet-stream

      - name: Upload Windows Release Asset (x64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/openorchid-${{ steps.get_version.outputs.version }}-win-x64.zip
          asset_name: openorchid-${{ steps.get_version.outputs.version }}-win-x64.zip
          asset_content_type: application/octet-stream

      - name: Upload MacOS Release Asset (arm64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/openorchid-${{ steps.get_version.outputs.version }}-mac-arm64.zip
          asset_name: openorchid-${{ steps.get_version.outputs.version }}-mac-arm64.zip
          asset_content_type: application/octet-stream

      - name: Upload MacOS Release Asset (x64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/openorchid-${{ steps.get_version.outputs.version }}-mac-x64.zip
          asset_name: openorchid-${{ steps.get_version.outputs.version }}-mac-x64.zip
          asset_content_type: application/octet-stream

    strategy:
      matrix:
        platform: [linux-arm, linux-arm64, linux-ia32, linux-x64, win-ia32, win-x64, mac-arm64, mac-x64]
